routes/web.php
<?php

use Illuminate\Support\Facades\Route;

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::get('/', function () {
    return view('welcome');
});


Route::group(['prefix' => 'users', 'as' => 'users.'], function () {
		Route::get('/register', ['as'=>'register','uses'=>'App\Http\Controllers\UserController@register']);
		Route::post('/store', ['as'=>'store','uses'=>'App\Http\Controllers\UserController@store']);
		Route::post('/login', ['as'=>'login','uses'=>'App\Http\Controllers\UserController@login']);
		Route::get('/list', ['as'=>'list','uses'=>'App\Http\Controllers\UserController@list']);
		Route::get('/edit/{id}', ['as'=>'edit','uses'=>'App\Http\Controllers\UserController@edit']);
		Route::post('/edit/{id}', ['as'=>'update','uses'=>'App\Http\Controllers\UserController@update']);
		Route::post('/delete/{id}', ['as'=>'delete','uses'=>'App\Http\Controllers\UserController@delete']);
		Route::post('/logout', ['as'=>'logout','uses'=>'App\Http\Controllers\UserController@logout']);
	});

resources/views/edit.blade.php
<!DOCTYPE html>
<html lang="en">
<head>
<meta charset="utf-8">
<meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
<title>Interview Test</title>
<link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.5.0/css/bootstrap.min.css">
<link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/font-awesome/4.7.0/css/font-awesome.min.css">
<script src="https://code.jquery.com/jquery-3.5.1.min.js"></script>
<script src="https://cdn.jsdelivr.net/npm/popper.js@1.16.0/dist/umd/popper.min.js"></script>
<script src="https://stackpath.bootstrapcdn.com/bootstrap/4.5.0/js/bootstrap.min.js"></script>
<style>
.login-form {
    width: 340px;
    margin: 50px auto;
  	font-size: 15px;
}
.login-form form {
    margin-bottom: 15px;
    background: #f7f7f7;
    box-shadow: 0px 2px 2px rgba(0, 0, 0, 0.3);
    padding: 30px;
}
.login-form h2 {
    margin: 0 0 15px;
}
.form-control, .btn {
    min-height: 38px;
    border-radius: 2px;
}
.btn {        
    font-size: 15px;
    font-weight: bold;
}
</style>
</head>
<body>
<div class="login-form">
    <form action="{{ route('users.update',$user->id) }}" method="post">
		@csrf
        <h2 class="text-center">User Info</h2>    
		<input type="hidden" name="token" value="{{ $token }}">
        <div class="form-group">
            <input type="email" class="form-control" placeholder="Email" name="email" value="{{ $user->email }}" required="required">
        </div>
        <div class="form-group">
            <input type="text" class="form-control" placeholder="Name" name="name" value="{{ $user->name }}" required="required">
        </div>
        <div class="form-group">
            <button type="submit" class="btn btn-primary btn-block">Submit</button>
        </div>
		<div class="clearfix">
            <a href="{{ route('users.list') }}?token={{ $token }}" class="float-right">Back</a>
        </div>  		
    </form>
</div>
</body>
</html>

resources/views/register.blade.php
<!DOCTYPE html>
<html lang="en">
<head>
<meta charset="utf-8">
<meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
<title>Interview Test</title>
<link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.5.0/css/bootstrap.min.css">
<link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/font-awesome/4.7.0/css/font-awesome.min.css">
<script src="https://code.jquery.com/jquery-3.5.1.min.js"></script>
<script src="https://cdn.jsdelivr.net/npm/popper.js@1.16.0/dist/umd/popper.min.js"></script>
<script src="https://stackpath.bootstrapcdn.com/bootstrap/4.5.0/js/bootstrap.min.js"></script>
<style>
.login-form {
    width: 340px;
    margin: 50px auto;
  	font-size: 15px;
}
.login-form form {
    margin-bottom: 15px;
    background: #f7f7f7;
    box-shadow: 0px 2px 2px rgba(0, 0, 0, 0.3);
    padding: 30px;
}
.login-form h2 {
    margin: 0 0 15px;
}
.form-control, .btn {
    min-height: 38px;
    border-radius: 2px;
}
.btn {        
    font-size: 15px;
    font-weight: bold;
}
</style>
</head>
<body>
<div class="login-form">
    <form action="{{ route('users.store') }}" method="post">
		@csrf
        <h2 class="text-center">Registration</h2>    
        <div class="form-group">
            <input type="email" class="form-control" placeholder="Email" name="email" value="" required="required">
        </div>
        <div class="form-group">
            <input type="text" class="form-control" placeholder="Name" name="name" value="" required="required">
        </div>
		<div class="form-group">
            <input type="password" class="form-control" placeholder="Password" name="password" value="" required="required">
        </div>
        <div class="form-group">
            <button type="submit" class="btn btn-primary btn-block">Register</button>
        </div>
		<div class="clearfix">
            <a href="{{ url('/') }}" class="float-right">Back</a>
        </div>  		
    </form>
</div>
</body>
</html>

resources/views/users.blade.php
<!DOCTYPE html>
<html lang="en">
<head>
  <title>Interview Test</title>
  <meta charset="utf-8">
  <meta name="viewport" content="width=device-width, initial-scale=1">
  <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.4.1/css/bootstrap.min.css">
  <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.5.1/jquery.min.js"></script>
  <script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.4.1/js/bootstrap.min.js"></script>
</head>
<body>

<div class="container">
  <h2>User List</h2>      
  <table class="table">
    <thead>
	  <tr>
        <th>Current User : {{ $curr_user->name }}</th>
        <th class="text-right">
			<form action="{{ route('users.logout') }}" method="post">
			@csrf
			<input type="hidden" name="token" value="{{ $token }}">
			<button type="submit">Logout</button>
			</form>
		</th>
      </tr>
      <tr>
        <th>Name</th>
        <th>Email</th>
        <th></th>
        <th></th>
      </tr>
    </thead>
    <tbody>
	  @foreach($users as $user)
      <tr>
        <td>{{ $user->name }}</td>
        <td>{{ $user->email }}</td>
        <td><a href="{{ route('users.edit',$user->id) }}?token={{ $token }}">Edit</a></td>
        <td>
			<form action="{{ route('users.delete',$user->id) }}" method="post">
			@csrf
			<input type="hidden" name="token" value="{{ $token }}">
			<button type="submit">Delete</button>
			</form>
		</td>
      </tr>
	  @endforeach
    </tbody>
  </table>
</div>

</body>
</html>